
== 5.3 Required text

Many of the elements in SC 4 standards require specific wording, called required text or boilerplate text. The required text is managed in the version-controlled repository of ISO/TC 184/SC 4.

The repository is located under [GIT ISO URL]/projects/ISOTC184SC4/repos/boilerplate.
(Mirrored at https://github.com/metanorma/iso-tc184-sc4-boilerplate)

The required text is placed as fragments and is maintained to keep alignment with the ISO Directives (updated and validated using the change management process of ISO/TC 184/SC 4).

The required text is between two parts:
* the first part consists of:
** the name of the folder where the boilerplate text is defined;
** the identifier that is enclosed between the “:” and the final “]”.
* the second part is [end_folder].

The light-yellow box below shows, with a “lorem ipsum” example, how we present the required text in this document.

----
[General:SC4_xxxx]
lorem ipsum ...
[end_General]
----

Therefore, the required text shown in this document is included as an example, only for illustration.

Each working group is responsible for the management of the required text specific to the series of standards under their control.

The SC 4 Quality Committee is responsible for maintaining the repository.


== 6.7 EXPRESS schema documentation

NOTE Any of the requirements below that only apply to integrated resources are indicated as such.

=== 6.7.1 General requirements

The title of each clause or subclause in which a schema is declared shall be the schema name (without the “_schema” suffix, if this is part of the name), with underscores replaced by spaces, and with the initial character in upper case.

EXAMPLE 1 The title of the clause that documents a schema whose name is “dynamic_fluid_flow” is “Dynamic fluid flow”.

For parts of ISO 10303 that are in the integrated resources series, each schema shall be documented in a separate clause.

When referring to the elements of the EXPRESS language, EXPRESS reserved words (such as SCHEMA, ENTITY, WHERE) shall appear as all caps in a monospaced font.

NOTE 1 Such references in the documentation of a schema should not be necessary, as these words refer to the elements of the language itself.

When referring to elements of the schema, words and phases such as “type”, “schema”, and “entity data type” shall not be capitalized.

EXAMPLE 2 In text that refers to an entity data type, use the phrase “the <entity data type name> entity data type, not “the <entity data type name> ENTITY”.

In the documentation of a schema, the same English language words may be used to refer to an object in the real world or to a concept, and as the name of an EXPRESS data type that represents this object or concept. Use the following typographical convention to distinguish between these. If the referent is the object or concept, the word or phrase occurs in the same typeface as narrative text. If the referent is the EXPRESS data type, the word or phrase occurs in a bold typeface. Use bold typeface for the names of EXPRESS schemas, functions, rules, procedures, and attributes of entity data types where they appear in general text.

The name of an EXPRESS data type may be used to refer to the data type itself, or to an instance of the data type. The distinction between these uses is normally clear from the context. If there is a likelihood of ambiguity, the phrase “entity data type” or “instance(s) of” is included in the text.

NOTE 2 See the SC 4 Quality manual for the procedure for validation of EXPRESS schemas.

=== 6.7.2 Components of a clause that specifies an EXPRESS schema

Each clause that specifies an EXPRESS schema shall contain the following subclauses in the order given below:

----
x <schema name>
x.1 Introduction
x.2 Fundamental concepts and assumptions
x.3 <schema name> type definitions
x.4 <schema name> entity data type definitions
x.5 <schema name> rule definitions
x.6 <schema name> function definitions
----

If there is nothing contained in one of the subclauses, the subclause shall be omitted, and the remaining subclauses renumbered accordingly.

The subclause containing declarations of entity data types may also be titled “<schema name> entity definitions”. If this form is used, it shall be used consistently for all schemas defined in a single standard.



=== 6.7.3 Schema documentation requirements

The following rules shall apply to documenting the schema.

An example of the wording to introduce the schema clause is given below (see 5.3. for implementing the required text).

----
[General:SC4_express_schemaClause]
This clause defines the information requirements to which
implementations shall conform using the EXPRESS language as defined
in ISO 10303-11. The following EXPRESS declaration begins the
<schema name> and identifies the necessary external references.
[end_General]
----

The <schema name> should be replaced by the name of the schema as it appears in the schema declaration. This wording shall appear immediately following the clause heading. If there are no external references, the words “and identifies the necessary external references” shall be omitted.

The above text shall be followed by the schema declaration. The declaration shall include any interface statements (USE FROM or REFERENCE FROM) necessary for the schema. An example of the required text for the declaration is given below (see 5.3. for implementing the required text).

----
[General:SC4_express_schema-1]
EXPRESS specification:

*)
SCHEMA <schema_1 name>;
REFERENCE FROM <schema_2 name>
  (<e1 name,
   e2 name>);
(*
[end_General]
----

Where interface statements occur, place a note following the schema declaration that identifies the source(s) of the interfaced schema(s). These sources may be any of the following:
* another clause of the same part;
* another part of the same SC 4 standard;
* a different standard.

In the second and third cases the standard in which the interfaced schema is declared shall be listed as a normative reference (see ISO/IEC Directives, Part 2, 2018, Clause 15).

An example of the notes is given below:

----
[General: SC4_express_schema-2]
NOTE X      The schemas referenced above are specified in the following documents:
<schema_1>  Clause <n> of this document
<schema_2>  ISO <ISO standard and part number>
NOTE X      See Annex x for a graphical representation of this schema.
[end_General]
----

The elements of the note are arranged in two left-justified columns, without punctuation. The schema name shall be presented in bold face.

EXAMPLE The following example illustrates this type of note:

----
NOTE The schemas referenced above can be found in the following parts of ISO 10303:

product_definition_schema   ISO 10303-41
geometry_schema             ISO 10303-42
representation_schema       ISO 10303-43
----

=== 6.7.4 Introduction to schema

The introduction to the schema shall include the objectives of the schema and a description of its major components and key concepts.

This subclause is primarily text but may contain figures, such as an EXPRESS-G diagram that presents an overview of the entity data types contained in the schema. If included, this figure shall be referenced from a note.

An example of the required text to begin the introduction to each schema for schemas defined in integrated resources parts of ISO 10303 is given below (see 5.3 for implementing the required text).

----
[ISO_10303:10303_express_schema-3]
The subject of the <schema name> is . . . .
[end_ISO_10303]
----

=== 6.7.5 Fundamental concepts and assumptions

The fundamental concepts and assumptions are declarations of fact about the subject area of the schema. These facts have been used as the basis for developing the integrated resource and are essential to the reader’s understanding and using the standard.

Fundamental concepts and assumptions may be expressed in a general or structured form. The general form shall be text that describes the concepts and assumptions that underlie the schema. The structured form shall be a list formatted as described in ISO/IEC Directives, Part 2, 2018, Clause 23.

Fundamental concepts that apply to the entire standard covering multiple schemas shall be documented in an additional clause immediately following the terms and abbreviations clause. Extra clauses may be included if appropriate to precede collections of related schemas.

=== 6.7.6 Documentation of formal propositions

Formal propositions follow the EXPRESS declaration (types and entity data types), the definition of enumeration items (types only), or argument definitions (rules). Formal propositions are constraints that are computable, are written in EXPRESS, and are placed within the WHERE clause of the declaration of a type, entity data type, or rule. The following rules apply to formal propositions in the documentation of types (see 6.7.8), entity data types (see 6.7.9), or rules (see 6.7.10).

* The formal propositions shall be preceded by the underlined title “Formal propositions:” (<=== this title is to be underlined).

* When there is a local rule label in the EXPRESS specification, each formal proposition shall start with the local rule label and be followed immediately by a colon and a single space. The label shall be in boldface. The colon shall not be boldface.

EXAMPLE The following examples illustrate the layout and format of formal propositions:

----
WR1: The value of x shall be positive.
UR1: The name shall be unique.
----

* The ISO required verbal forms “shall” (see ISO/IEC Directives, Part 2, 2018, Clause 7) shall be used.
* Any additional explanation or examples shall be provided as notes (see ISO/IEC Directives, Part 2, 2018, Clause 24 ) or examples (see ISO/IEC Directives, Part 2, 2018, Clause 25 ).
* The order of the formal propositions shall be the same as the order of the constraint specifications in the EXPRESS declarations.
* There shall be a one-to-one correspondence between the local rules stated in the EXPRESS declaration (WHERE, INVERSE, and UNIQUE constraints) and the elements in the list of formal propositions.
* If a local rule uses a call to an EXPRESS function, the effect of the tests within that function as they are applied to this type or entity data type shall be briefly described. A statement that the function shall return the value TRUE is not adequate. A local rule is satisfied if the evaluated result of the rule expression is TRUE or UNKNOWN; a function used within a local rule may never return UNKNOWN.

==== 6.7.7 Documentation of informal propositions

Informal propositions are un-computable constraints that cannot, or cannot reasonably, be written in EXPRESS, although each informal proposition still represents a requirement. If an EXPRESS declaration exists or EXPRESS-like pseudo-code has been written, it may be included in an informative annex as a technical discussion. Each informal proposition shall be presented as follows.
* The informal propositions shall be preceded by the underlined title “Informal propositions:”.
* Each informal proposition shall be given a label, corresponding to the local rule labels that appear in formal propositions. By convention, informal propositions in ISO 10303 parts are labelled IP1, IP2, and so on.

NOTE Several legacy resources use a short English word for a label. That usage is acceptable only for those existing labels.

* The ISO required verbal forms “shall” (see ISO/IEC Directives, Part 2, 2018, Clause 7) shall be used.
* Any additional explanation or examples shall be provided as notes (see ISO/IEC Directives, Part 2, 2018, Clause 24) or examples (see ISO/IEC Directives, Part 2, 2018, Clause 25).

The explanation for each information proposition shall state the conditions and requirements that shall be met by instances of the type or the entity data type.

==== 6.7.8 Type documentation requirements

The following rules apply to the documentation of types.

* Document each type in the “<schema name> type definitions” subclause in a separate subclause. The title of the subclause shall be the name of the type exactly as it appears in the EXPRESS declaration (lower case with underscores).
* The title shall be followed by a textual definition of the type and any supporting material necessary to define the intent of the type. In particular, this text should demonstrate how this type is different from any other similar type.
* The EXPRESS declaration shall be given next using the format described in 6.2.9, separated from the text by comment markers as described in 6.2.4. The title “EXPRESS specification:” shall be placed immediately before the close-comment marker.
* If the type is an enumeration of items, the items may be defined following the EXPRESS declaration. Definitions of enumerated items shall be given for clarity, unless the item corresponds exactly to a term defined in the terms and definitions clause (see ISO/IEC Directives, Part 2, 2018, Clause 16) of the standard. If the enumeration item corresponds to a defined term, a reference to the definition of the term shall be included as a note. The title “Enumerated item definitions:” shall precede the definitions of the enumeration items. Each enumerated item definition shall consist of the identifier of the item in boldface, a colon, one space, and the definition of the item.
* If the type is an extensible select, the definition shall begin with a required wording, followed by any necessary explanation of the domain concepts. An example is given below (see 5.3 for implementing the required text).

----
[ISO_10303:10303_express_schema-select]
The <name of extensible select> type is an extension of the <name of select> type. It adds the data types <list of data types> to the list of alternate data types.

NOTE The list of entity data types may be extended in application modules that use the constructs of this module.
[end_ISO_10303]
----

* If the type is an extensible enumeration, the definition shall begin with the following wording, followed by any necessary explanation of the domain concepts.

----
[ISO_10303:10303_express_schema-enum]
The <name of extensible select> type is an extension of the <name of select> type. It adds the enumeration items <list of enumeration items > to the list of alternate enumeration items.

NOTE The list of enumerations may be extended in application modules that use the constructs of this module.
[end_ISO_10303]
----

* Formal propositions (see 6.7.6) follow the EXPRESS declaration or the definition of enumeration items.
* Informal propositions (see 6.7.7) follow the formal propositions


=== 6.7.9 Entity data type documentation

==== 6.7.9.1 General requirements

The entity data types declared in a schema shall be documented in a subclause titled ““<schema name> entity data type definitions” or “<schema name> entity definitions”. Entity data types may be collected into logical groups in order to enhance the readability and understandability of the schema. If such groups are used (there shall be at least two such groups), the following structure should be used for the entity definition subclause.

----
  x.y.1 <schemaname>entitydatatypedefinitions:<logicalgroupname1>
  x.y.2 <schemaname>entitydatatypedefinitions:<logicalgroupname2>
  x.y.3 <schemaname>entitydatatypedefinitions:<logicalgroupname3>
  ...
  x.y.n <schemaname>entitydatatypedefinitions:<logicalgroupnamen>
----

All EXPRESS entity data types shall be at the same subclause level within each group.

All EXPRESS entity data types within a given functional grouping should be presented in an order that will aid understanding. An obvious and common ordering will present the EXPRESS entity data types according to the subtype/supertype hierarchy relationships among the entity data types.

If there is no other reasonable order, the entities shall appear in alphabetical order.

==== 6.7.9.2 Documenting a single entity data type

NOTE 1 See 6.9.2 for an example of the documentation of an entity data type.

The following rules apply to documenting an entity data type.
* Each entity data type definition shall be a new subclause. The title of the subclause shall be the name of the entity data type exactly as it appears in the EXPRESS declaration (lower case with underscores). See 6.5.2.2 for the requirements that apply to naming of entity data types.
* The definition of an entity data type shall state clearly the following:
* the concept that the entity data type represents;
* the information about the concept that is represented in the data structure and constraints defined by the entity data type.

When the name of the entity data type without underscore and in normal text (not boldface) is used, it stands for the concept that the entity data type represents.

* The follow convention may be used to simplify entity data type definitions. The phrase “an *<entity_data_type_name>* is/represents ...” may be used as a short hand for “An instance of the *<entity_data_type_name>* entity data type is/represents ...”.
* Examples may be provided to clarify the concept that is represented by the entity data type or to illustrate the population of the entity data type and its attributes. It shall be clear whether each example refers to the concept represented by the entity data type or the data that is governed by the entity data type. Examples follow the prose definition.
* Extra explanations and references to other sources for explanations should be given as one or more notes.
* Tables or figures may be included in the definition of an entity data type. If the information conveyed in the table or figure is essential to understanding of the entity data type, the table or figure shall be referenced from the normative text of the definition so that it is itself normative. If the information conveyed in the table or figure enhances but is not essential to understanding the entity data type, the table or figure shall be referenced from a suitable note or example so that it is itself informative.

The EXPRESS declaration for the entity data type follows the definition. The declaration shall be introduced by the underlined title “EXPRESS specification:” and delimited by comment markers as specified in 6.2.4.

Following the EXPRESS declaration, all attributes (both explicit and derived) shall be documented. The attribute definitions shall be introduced by the underlined title “Attribute definitions:”. The following rules apply to the documentation of attribute definitions:
* The attributes shall be documented in the same order as they appear in the EXPRESS declaration.
* The attribute definitions shall be presented as follows.

** Each attribute definition shall start with the attribute name exactly as given in the EXPRESS declaration (complete with underscores), in boldface, and followed by a colon.

** The definition of the attribute shall follow the name of the attribute, starting on the same line.
** The definition of the attribute shall describe the role of that attribute in the entity data type. If the attribute uses another entity data type or type, there is no need to give a definition for the referenced item.

NOTE 2  If it appears necessary to redefine the referenced item, indicating that meaning of the referenced type varies according to its use, consider defining a new intersection entity data type.

* Additional explanation may be given as notes.
* Examples that illustrate the population or usage of the attribute may also be given.

Formal propositions (see 6.7.6) follow the attribute definitions.

Informal propositions (see 6.7.7) follow the formal propositions.

==== 6.7.9.3 References to attributes declared in supertypes

A reference to an attribute declared in a supertype may be explained with a note following the first use of the attribute name.

EXAMPLE The following example illustrates the wording of such a note:

----
NOTE The attribute <a_name> is declared in the <e_name> entity data type of which this entity data type is a subtype.
----

==== 6.7.9.4 Plurals of

Avoid using plurals of EXPRESS object names by an alternate usage, such as “several instances of the *vertex* entity data type.” If necessary, plurals of EXPRESS object names may be made by adding an “s” (not in boldface) to the end of the name. This includes names for which the plural in English changes the spelling of the word.

EXAMPLE The following example illustrates the addition of an “s” to refer to multiple instances of the vertex entity data type: “An *open_path*) visits its **vertex**s exactly once.”.

NOTE The wording specified in the example above is much clearer if changed to: “Each instance of open_path visits each of its instances of *vertex* exactly once.”.

=== 6.7.10 Rule documentation requirements

The following requirements apply to documenting rules.
* All rules shall be declared/defined in the “<schema name> rule definitions” subclause.
* Each rule shall constitute a new subclause. The title shall be the name of the rule exactly as it appears in the EXPRESS declaration (lower case with underscores). This name should not be abbreviated and should comprise, where possible, proper English words (see 6.5.2.6 for constraints on the maximum length of EXPRESS identifiers).
* If there is only one rule declaration in a schema, the rule declaration shall appear in a single subclause titled “<schema name> rule definition: <rule name>”.
* The title shall be followed by a prose definition and any supporting text necessary to state the intent of the rule.
* The EXPRESS declaration shall follow the definition, preceded by the underlined title “EXPRESS specification:”.
* The arguments of the rule shall be defined following the EXPRESS declaration, preceded by the underlined title “Argument definitions:”.
* The argument definitions shall be presented as follows.
** Each argument definition shall start with the argument name exactly as given in the EXPRESS declaration (complete with underscores), in boldface, followed by a colon.
** The definition of the argument shall follow the name of the argument, starting on the same line.

* Each constraint within the WHERE clause of the rule shall have a unique label. Unless an appropriate short English word can be used, the form of the label shall be WRn where n is an integer giving the position of the rule in the list.

NOTE By convention, schemas defined in parts of ISO 10303 use the WRn form only.

* Each constraint within the WHERE clause of the rule shall be documented as a formal proposition (see 6.7.6). The formal propositions follow the argument definitions.
* If a constraint is dependent on an unelaborated function or procedure (see 6.7.12), this should be stated in a note.

EXAMPLE The following example illustrates the wording of such a note.

NOTE This rule is based on an unelaborated EXPRESS function.

=== 6.7.11 Subtype constraint documentation requirements

The following requirements apply to documenting subtype constraints.
* All subtype constraints shall be declared/defined in the “<schema name> subtype constraint definitions” subclause.
* Each subtype constraint shall constitute a new subclause. The title shall be the name of the subtype constraint exactly as it appears in the EXPRESS declaration (lower case with underscores). This name should not be abbreviated (see 6.5.2.6 for constraints on the maximum length of EXPRESS identifiers).
* If there is only one subtype constraint declaration in a schema, the declaration shall appear in a single subclause titled “<schema name> subtype constraint definition: < subtype constraint name>”.
* The title shall be followed by a prose definition and any supporting text necessary to state the intent of the subtype constraint.
* The EXPRESS declaration shall follow the definition, preceded by the underlined title “EXPRESS specification:”.

=== 6.7.12 Function (procedure) documentation requirements

==== 6.7.12.1 General requirements

The following rules apply to documenting function (or procedure) definitions:
* All functions shall be declared/defined in the “<schema name> function definitions” subclause.
* Each function shall constitute a new subclause. The title shall be the name of the function exactly as it appears in the EXPRESS declaration (lower case with underscores). The name should not be abbreviated (see 6.5.2.6 for constraints on the maximum length of EXPRESS identifiers).
* If there is only one function declaration in a schema, it should appear in a single subclause titled <schema name> function definition: “<function name>“.
* The title shall be followed by a definition and any supporting text necessary to define the intent of the function.
* The EXPRESS declaration shall follow the definition, preceded by the underlined title “EXPRESS specification:”.
* The arguments of the function shall be defined following the EXPRESS declaration, preceded by the underlined title “Argument definitions:”.
* The argument definitions shall be presented as follows.
** Each argument definition shall start with the argument name exactly as given in the EXPRESS declaration (complete with underscores), in boldface, followed by a colon.
** The definition of the argument shall follow the name of the argument, starting on the same line. Each definition shall include whether the argument is an input, output, or both, and enumerate and define any error conditions that may result from the function.

EXPRESS functions and procedures and their application to entities may be documented by three different methods according to the completeness of the specification included in the standard. These methods are as follows:
* functions and procedures that are fully specified in EXPRESS (see 6.7.12.2);
* functions and procedures that cannot, or cannot easily, be specified in EXPRESS but can be implemented within a specific application system (see 6.7.12.3);
* functions or procedures that cannot be implemented at all, either within EXPRESS or within an application system (see 6.7.12.4).

When the EXPRESS declaration of a function is not or cannot be explicitly specified, an EXPRESS comment should replace the body of the function stating the following:
* why the appropriate EXPRESS language statements are missing;
* what the function is intended to do.

==== 6.7.12.2 Functions and procedures fully specified in EXPRESS

Functions and procedures fully specified in EXPRESS shall be documented as follows.
* The full EXPRESS specification of the function or procedure shall be documented in an appropriate subclause.
* The function or procedure shall be used as part of the definition of a constraint in one or more types or entity data types.

EXAMPLE 1 The following example illustrates a fragment of the EXPRESS declaration for a fully specified function:

EXAMPLE 2 The following example illustrates a fragment of the EXPRESS declaration of an entity data type that uses the function illustrated above to define a constraint:

----
*)
FUNCTION function_name (x:INTEGER): LOGICAL;

<function body in EXPRESS>

END_FUNCTION;
(*
----

----
*)
ENTITY foo;
...
WHERE
  WR1: function_name(...); END_ENTITY;
(*
...

Formal propositions:

WR1: xxx;
----


==== 6.7.12.3 Functions and procedures that can be implemented within a specific application system

Functions and procedures that cannot, or cannot easily, be implemented in EXPRESS but can be implemented within a specific application system, shall be documented as follows.
* The EXPRESS specification of the function or procedure shall include the phrase “unelaborated function/procedure” as a tail remark together with text describing the intent of the function.
* The function or procedure shall be used as part of the definition of a constraint in one or more types or entity data types.

EXAMPLE 1 The following example illustrates a fragment of the EXPRESS declaration for an unelaborated function:

----
*)
FUNCTION function_name (x:INTEGER): LOGICAL;

-- unelaborated function

(* <text that explains the intent of the function. Note that the
text is commented out between the function head and tail.> *)

END_FUNCTION;
(*
----

The tail comment shall be inserted as shown so that it will occur in the EXPRESS listing of the schema.

An explanation of why the function is not elaborated may be placed in a note following the textual description of the function.

EXAMPLE 2 The following example illustrates a fragment of the EXPRESS declaration of an entity data type that uses the function illustrated above to define a constraint:

----
*)
ENTITY foo;
...
WHERE
  WR1: function_name(...); END_ENTITY;
(*

...

Formal propositions:

WR1: xxx;

NOTE This proposition is based upon an unelaborated EXPRESS function or procedure.
----

The note following the formal proposition shall be included to indicate that an EXPRESS declaration for the function exists, but that it has not been elaborated.

==== 6.7.12.4 Constraints that cannot be implemented

Not all constraints can be implemented in a uniform manner, either within EXPRESS or within an application system.

Such constraints shall be documented as follows:

* If the constraint applies to a single entity data type, it shall be defined in an informal proposition (see 6.7.7) within the documentation of that entity data type.
* If the constraint applies to two or more entity data types, it shall be defined as a pseudo-function, in a separate subclause. However, no EXPRESS declaration shall be given.

==== 6.7.13 End of schema declaration

The EXPRESS declaration shall be the last item of the last subclause within each schema clause. The text below is shown as example (see 5.3 for implementing the required text).

----
[General:SC4_express_schema-end]
*)
END_SCHEMA; -- <schema name>
(*
[end _General]
----

= 8 ISO 10303 series: additional requirements for structure and content of parts

== 8.1 General

For all parts in the ISO 10303 series, the following documents provide applicable requirements:

* ISO/IEC Directives, Part 2, 2018, Principles and rules for the structure and drafting of ISO and IEC documents;
* the ISO Simple template;
* ISO 10303-1, Industrial automation systems and integration — Product data representation and exchange — Part 1: Overview and fundamental principles.

In addition, Clause 5 of this document (Requirements for the structure and content of SC4 standards) applies.

* the following individual groups of parts within the ISO 10303 series have specific documentation requirements:
** the integrated resources series (see 8.2);
** the application protocol series (see 8.3);
** the application module series (see 8.4);
** the domain model series (see 8.5).

Single quotation marks are used to denote literal text string values. Double quotation marks follow standard British usage, for direct quoted material presented within other material, and titles of works following a specific bibliographic format. While quotation marks may be used to identify words being discussed as words, this usage is unlikely within the context of ISO 10303.

=== 8.1.1 ISO 10303 series required text

For all the documents of the ISO 10303 series a specific wording is required.

This specific wording is defined and managed by the working group responsible for the series and is available in a shared repository.

The repository is located under [GIT ISO URL]/projects/ISOTC184SC4/repos/boilerplate.

Each writer shall ensure that the boilerplate text in an SC 4 standard conforms to the boilerplate text released in the repository.

A guide “How to use the required text” is at Annex C of this document.

=== 8.1.2 Documentation of Introduction

The start of the introduction of each part of ISO 10303 is a required text (see 5.3 for implementing the required text).

An example reads as follows:

----
[ISO_10303:10303_introduction]
ISO 10303 is an International Standard for the computer-interpretable representation of product information and for the exchange of product data. The objective is to provide a neutral mechanism capable of describing products throughout their life cycle. This mechanism is suitable not only for neutral file exchange, but also as a basis for implementing and sharing product databases, and as a basis for retention and archiving.
[end_ISO_10303]
----

=== 8.1.3 Computer interpretable listing annex

==== 8.1.3.1 Documents that include EXPRESS

This annex shall provide electronic access to the list of short names provided in the annex “short names” and the EXPRESS specified in the part. This access is provided through the specification of URLs that identify the location of these files on the Internet. The EXPRESS file shall not contain any intervening prose; the EXPRESS listing for all schemas shall be found in one file. The listing shall not contain any comment delimiters of the kind “*)” and “(*” that separate the EXPRESS declarations from the main body of the prose. However, tail comments (those beginning with “--”) may be included.

The text of this annex is an ISO 10303 required text (see 5.3 for implementing the required text).

An example reads as follows:

----
[ISO_10303:10303_annex-comp-int]

This annex references a listing of the EXPRESS entity names and
corresponding short names as specified or referenced in this
document. It also provides a listing of each EXPRESS schema
specified in this document without comments or other explanatory
text. These listings are available in computer-interpretable form in
Table C.1 and can be found at the following URLs:

  Short names:  http://standards.iso.org/iso/10303/tech/short_names/short-names.txt
  EXPRESS:      http://standards.iso.org/iso/10303/smrl/v8/tech/smrlv8.zip

<insert table C.1– EXPRESS listings>

NOTE The information provided in computer-interpretable form at the
above URLs is informative. The information that is contained in the
body of this document is normative.

[end_ISO_10303]
----

==== 8.1.3.2 Documents that don’t include EXPRESS

Please refer to the N Document guidelines or adapt the text as appropriate.

=== 8.1.4 EXPRESS-G diagram annex

The EXPRESS-G diagrams describing the schema(s) defined in the part shall be included as a set of figures in this annex. Rules for formatting these diagrams are found in 6.8.

The text used to introduce the EXPRESS-G diagrams and to list the captions of each figure containing an EXPRESS-G diagram is a required text (see 5.3 for implementing the required text).

An example reads as follows:

----
[ISO_10303:10303_annex-expg-1]

The diagrams in this annex correspond to the EXPRESS schemas specified in this document. The diagrams use the EXPRESS-G graphical notation for the EXPRESS language. EXPRESS-G is defined in Annex D of ISO 10303-11.

[end_ISO_10303]
----

----
[ISO_10303:10303_annex_expg-1]

Figure <X>.<n> — EXPRESS-G diagram of the <schema_name> (<x> of< y>)

[end_ISO_10303]
----

where <X> is the annex number, <n> is the diagram number, and <x>,<y> are the ranges of the related figures for one schema.

EXAMPLE From ISO 10303-42:2019:

    Figure D.1 — EXPRESS-G diagram of the geometry_schema (1 of 16);


=== 8.1.5 SCHEMA names

Schema names in the ISO 10303 integrated resources shall end with “_schema”. Schema names in ISO 10303 application interpreted constructs shall begin with “aic_”. ARM schema names in ISO 10303 modules shall end with “_arm”. MIM schema names in ISO 10303 modules shall end with “_mim”.

Shortform schema names shall end with _arm and _mim, but longform schema names shall end with _arm_lf and _mim_lf.

== 8.2 Documentation of Integrated resources series (IR)

=== 8.2.1 General

For the documentation of the integrated resources series of parts for ISO 10303 the following documents apply:

* Documents listed in 8.1;
* ISO/TC 184/SC 4 N1548 — Guidelines for the format and layout of SC4 standards using HTML.
* ISO 10303 IR standard developers may use the STEPmod documentation environments depending on the scope of their standard. Guidelines for these are available here: STEPmod Tutorial [18].

A set of IRs (see 3.4.14) shall provide the specification of a representation of product information. Each IR comprises a set of descriptions, written in a formal data specification language, applicable to product data known as resource constructs. One set may be dependent on other sets for its definition. A single resource construct (See 3.4.20) may represent similar information for different applications.

The IRs in ISO 10303 are divided into two groups: generic resources (See 3.4.11) and application resources (See 3.4.6). The generic resources are independent of applications and may reference other resources. The application resources may reference other resources and may add other resource constructs for use by a group of similar applications. The IRs may reference product data descriptions written using EXPRESS from other International Standards.

Each part of ISO 10303 in the integrated resources series includes a clause for each schema that is documented in the part. See Clause 6 for requirements that apply to documenting EXPRESS schemas.

EXAMPLE
----
The clauses 4 to 7 of the ISO 10303-42 are the following:

4 Geometry, which is the Geometry schema
5 Topology, which is the Topology schema
6 Geometric model, which is the Geometric model schema
7 Scan data 3d shape model, which is the Scan data 3d shape model schema
----

This section uses the following convention to delineate annexes that are to be included, they are enclosed in light grey box, the header gives the “mandatory/optional/conditional” status.

=== 8.2.2 Content of an integrated resource

The contents of an integrated resource shall be composed of the elements listed in the Table 1 — Overview of the major subdivisions of a document and their arrangement in the text and at least of the following mandatory annexes:

----
[ISO 10303 mandatory]

A Short names of entities (Normative)
B Information object registration (Normative)
C Computer interpretable listings (Informative)
D EXPRESS-G diagrams (Informative)

[end mandatory]
----

Conditional informative annexes may be included. They shall be lettered sequentially. Such annexes may include the following:

----
[ISO 10303 conditional]

E Change history (Informative)

[end conditional]
----

Additional informative annexes may be included if they provide additional information that helps the reader to understand the schemas documented in the part. They shall be lettered sequentially. Such annexes may include the following:

----
[ISO 10303 optional]

F Technical discussions (Informative)
G Examples (Informative)
H Additional scope information that crosses multiple schemas or integrated resources parts.

[end optional]
----

=== 8.2.3 Documentation of Introduction

The start of the introduction of each part of ISO 10303 that is a member of the integrated resources series is an ISO 10303 required text (see 5.3 for implementing the required text).

An example reads as follows:

----
[ISO_10303:10303_introduction]

ISO 10303 is an International Standard for the
computer-interpretable representation of product information and for
the exchange of product data. The objective is to provide a neutral
mechanism capable of describing products throughout their life
cycle. This mechanism is suitable not only for neutral file
exchange, but also as a basis for implementing and sharing product
databases, and as a basis for retention and archiving.

[end_ISO_10303]
----

For the parts with more than one schema, use the following:

----
[ISO_10303_IR:10303_IR_introduction-1]

Major subdivisions of this document are: <use list format to list
the names of the schemas, or descriptions of groups of schemas>.

[end_ISO_10303_IR]
----

This wording may be followed by one or more paragraphs that provide an overview of the schema or schemas, without stating requirements. If information from the scope clause is repeated, use the same wording as in the scope.

In an integrated resources part, include a schema level model that illustrates the schema(s) specified in the context of the integrated resources as a whole, introduced by the following wording:

----
[ISO_10303_IR:10303_IR_introduction-2]

The relationships of the schemas in this document to other schemas
that define the integrated resources of ISO 10303 are illustrated in
Figure <figure number> using the EXPRESS-G notation. EXPRESS-G is
defined in Annex D of ISO 10303-11.

The <list schemas from other parts depicted in the diagram> are
specified in <list the parts>. The schemas illustrated in Figure
<figure number> are components of the integrated resources.

[end_ISO_10303_IR]
----

=== 8.2.4 Documentation of scope

The scope clause of a part of ISO 10303 in the integrated resources series provides a clear explanation of the technical boundaries addressed by the schemas specified in the part. For an integrated generic resource part, the scope describes the domain of applicability. For an integrated application resource part, the scope describes the application area.

An example of the wording to introduce the scope clause of a part of ISO 10303 that is a member of the integrated resources series is given below, followed by the SC 4 wording (See 5.5.4 for general SC 4 requirements for the wording of the scope clause and see 5.3 for implementing the required text).

----
[ISO_10303_IR:10303_IR_scope-1]
This document specifies the integrated generic resource constructs for
[end_ISO_10303_IR]
----

This is followed by more detailed information in the form of a list as to what is within the scope of the document:

----
[General:SC4_Scope_scope-2]
The following is (are) within the scope of this document: <list of in-scope elements>
[end_General]
----

After this, the following optional text introduces information that is outside the scope of the document:

----
[General:SC4_Scope_scope-3]
The following is (are) outside the scope of this document: <list of out-scope elements>
[end _General]
----

The primary mechanism for defining the scope of each part in the integrated resources series is a simple text explanation of the information content of the part. At the minimum, an integrated resource part shall contain a narrative description of the scope of the information represented by the schema. It should describe the application area being addressed and any boundaries, limits, or rules used to determine whether something is in scope.

=== 8.2.5 Documentation of normative references

Each part of ISO 10303 that is related to the integrated resource constructs being documented shall be identified as a normative reference. A part of ISO 10303 containing a schema that is identified by a *REFERENCE FROM* EXPRESS statement in the integrated resource being documented is related and shall be listed as a normative reference.

=== 8.2.6 Documentation of the index

The index shall contain references to the declaration of each type, entity data type, function, and rule in the standard. The index shall reference the page on which the EXPRESS language statements of the declaration begin, rather than the page on which the clause or subclause containing the declarations begin.

NOTE Because the underlined heading “EXPRESS specification” immediately precedes the EXPRESS declaration and always appears on the same page, this heading can be used as the target for the index entry.

The index shall contain only a single index entry for each EXPRESS element. Each index item shall contain only a single page number for each EXPRESS element.

The index may contain additional reference information; however, it shall not include the references from other EXPRESS declarations for an EXPRESS element index entry.

=== 8.3 Documentation of the application protocol series of parts for ISO 10303

For the documentation of the application protocol series of parts for ISO 10303 the following documents apply:

* Documents listed in 8.1;
* ISO/TC 184/SC 4 N1548 — Guidelines for the format and layout of SC4 standards using HTML;
* ISO/TC 184/SC 4 N1863 — Guidelines for the content of application protocols that use application modules;
* ISO/TC 184/SC 4 N2661 — Guidelines for the development of mapping specifications;
* ISO/TC 184/SC 4 N3501 — STEP extended architecture high-level description;
* ISO/TC 184/SC 4 N3503 — STEP extended architecture detailed STEPlib specifications
* ISO/TC 184/SC 4 N3504 — STEP extended architecture publication design.

Editors shall also take note of the following documents:

* ISO/TC 184/SC 4 N1337 [19] — Application module development points within the application
protocol development process.
* ISO 10303 standard developers may use the STEPmod and STEPlib documentation environments depending on the scope of their standard. Guidelines for these are available here: STEPmod Tutorial [18] and Extended Architecture usage guide for developers and publishers [20]

== 8.4 Documentation of the application module series of parts of ISO 10303

For the documentation of the application module series of parts for ISO 10303 the following documents apply:

* Documents listed in 8.1;
* ISO/TC 184/SC 4 N1337 — Application module development points within the application protocol development process;
* ISO/TC 184/SC 4 N1548 — Guidelines for the format and layout of SC4 standards using HTML;
* ISO/TC 184/SC 4 N1685 — Guidelines for the content of application modules;
* ISO/TC 184/SC 4 N2661 — Guidelines for the development of mapping specifications. Use of STEPmod by AM development teams is mandatory. See the STEPmod Tutorial [18].

== 8.5 Documentation of the domain model series of parts for ISO 10303

For the documentation of the domain model series of parts for ISO 10303 the following documents apply:

* Documents listed in 8.1;
* ISO/TC 184/SC 4 N3501 — STEP extended architecture high-level description;
* ISO/TC 184/SC 4 N3503 — STEP extended architecture detailed STEPlib specifications;
* ISO/TC 184/SC 4 N3504— STEP extended architecture publication design.
* ISO 10303 standard developers may use the STEPlib documentation environments depending on the scope of their standard. Guidelines for these are available here: Extended Architecture usage guide for developers and publishers [20]
